### ISSUE TITLE
[BUG] When spectating a player in First person Spec, the muzzle flash exiting the gun is on the right side of the gun rather than coming out of the barrel

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#419] opened 2024-06-29 20:18 UTC
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

When you spectate someone, the muzzle flash coming out of their gun does not exit from the barrel, rather a bit right from the gun's barrel.

### To Reproduce

1. Spectate a player

### Expected behavior

Muzzle flash should be coming out from the barrel of the gun

### Actual behavior

Muzzle flash is coming from the right side of the barrel

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

**Comment by Rainyan** [comment] 2024-06-29 20:22
If this is exclusive to the Tachi, then this is a duplicate of: #365

**Comment by kassibuss** [comment] 2024-06-29 20:37
@Rainyan I saw this happen with other weapons such as the MX

**Comment by AdamTadeusz** [comment] 2024-09-25 11:11
> @Rainyan I saw this happen with other weapons such as the MX

Can you replicate this happening with the mx?

**Comment by AdamTadeusz** [comment] 2024-10-03 14:56
Closed, duplicate of https://github.com/NeotokyoRebuild/neo/issues/365

**Closed by AdamTadeusz** 2024-10-03 14:56 UTC
Labels: bug
