### ISSUE TITLE
Guns never fall through floors

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#277] opened 2024-05-27 16:12 UTC
Guns falling through floor. - Bauxite

**Comment by nullsystem** [comment] 2024-06-15 21:15
Linked the PR and closed as fixed: `mp_weaponstay 1` - Weapons stays throughout round, ghost stays

**Comment by Rainyan** [comment] 2024-06-16 01:09
> Linked the PR and closed as fixed: mp_weaponstay 1 - Weapons stays throughout round, ghost stays

The issue description is kind of vague, but are we sure this doesn't relate to some kind of collision bug? Original NT was notorious to have the ghost fall through the floor when the holding player died, presumably because it was ejected from player's absorigin which is near the feet, and sometimes the physics system resolved it as being under the floor instead of atop of it. But I think this could also happen with other guns in OG NT, but the ghost bugging out was the most noticeable one because of its disruptiveness.

@kassibuss @nullsystem

**Comment by blaberry** [comment] 2024-06-27 20:55
I'm not sure this is fixed, like rain said. I think this is due to dropped weapons under some circumstances spawning at the player origin (which may end up sending them into the void.)

**Comment by nullsystem** [comment] 2024-07-31 17:03
If this is about a player holding a weapon and died, then #502 may have already fixed it since the fix also applied for any weapons dying player was holding not just the ghost.

**Comment by blaberry** [comment] 2024-08-01 14:54
Let's close this as it seems irreproducible. If it's still an issue, it'll come up again.

**Closed by blaberry** 2024-08-01 14:54 UTC
Labels: bug, Gameplay, Poor Description
