### ISSUE TITLE
Players don't collide with each other

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#205] opened 2024-05-17 20:22 UTC

**Comment by nullsystem** [comment] 2024-05-17 21:07
Wasn't this already done? https://github.com/NeotokyoRebuild/neo/pull/17

**Comment by nullsystem** [comment] 2024-06-15 12:09
Dupe of: https://github.com/NeotokyoRebuild/neo/issues/56

**Closed by nullsystem** 2024-06-15 12:09 UTC
Labels: duplicate, General Plugin
