### ISSUE TITLE
Shrine

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#28] opened 2024-05-14 21:46 UTC

**Comment by kassibuss** [comment] 2024-06-11 12:20
Since there wasnt a description in the original issue, the problem seems to be caused by displacements on the map. To paraphrase destroygirl: 
"You have to set the displacements to the power of 2", but doing that on shrine causes the displacements to become so wonky that you can see into the skybox through them. I think the solution is just to recompile the culrpit maps on SDK13 tools.

**Comment by blaberry** [comment] 2024-07-05 14:44
test.

**Comment by AdamTadeusz** [comment] 2024-10-03 14:53
Closed in favor of https://github.com/NeotokyoRebuild/neoAssets/issues/1

**Closed by AdamTadeusz** 2024-10-03 14:53 UTC
Labels: Map Issues
