### ISSUE TITLE
Team score in team selection menu reflect W/L/T

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#139] opened 2024-05-14 22:18 UTC
**Issue:**
When chosing team, the Score reflects the number of kills made by that team.

**Resolution:**
Score is not number of round wins, not kills made. 

![Image](https://github.com/user-attachments/assets/0d70285b-2f5e-4b92-ae2a-8ed1653cf0d8)

This has been resolved. TODO: find the PR.

**Comment by AdamTadeusz** [comment] 2024-07-13 10:32
Possibly a duplicate of  #54?

**Comment by kassibuss** [comment] 2024-07-31 17:26
fixed by https://github.com/NeotokyoRebuild/neo/pull/263

**Closed** 2024-07-31 17:29 UTC
Labels: Gameplay, Poor Description
