### ISSUE TITLE
Dawn crashes the server

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#592] opened 2024-09-16 08:51 UTC
### Build Info

20240914_b2291c5

### Description

About twenty seconds into warmup on the map dawn, the server crashes.

### To Reproduce

1. rtv nt_dawn_ctg
2. play a couple of seconds of warmup
3. experience unscheduled rapid server maintenance

### Expected behavior

the server doesn't crash

### Actual behavior

the server crashes.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Win 10

### Machine's CPU

Ryzen 9 7950X

### Machine's GPU

RTX 3080 FE

### GPU's driver

Nvidia 556.12

### Build's compiler

MSVC 19.41.34120.0

**Comment by AdamTadeusz** [comment] 2024-09-16 10:47
possible duplicate of  #551

**Comment by AdamTadeusz** [comment] 2024-10-03 14:54
Closed in favor of https://github.com/NeotokyoRebuild/neoAssets/issues/1

**Closed by AdamTadeusz** 2024-10-03 14:54 UTC
Labels: Map Issues, Bug Report
